---
name: Deploy to DataHub running on EC2
on:
  # Trigger the workflow on push to main branch
  push:
    branches: [ main ]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
		
    - name: Upload file to S3
      env:
        FILE_PATH: ./metadata_ingestion/glossary_yaml_ingestion/taxi-driver/*.yml
        S3_BUCKET_NAME: datahubch/github-data
      run: |
        aws s3 cp $FILE_PATH s3://$S3_BUCKET_NAME/ --region eu-west-1
        
    - name: Copy File to EC2
      env:
        EC2_INSTANCE_ID: i-02134150d4b26a52c
        S3_BUCKET_NAME: datahubch/github-data
        DESTINATION_PATH: /home/ubuntu/DataHubIngestionCICD
      run: |
        aws ssm send-command \
          --instance-ids $EC2_INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --parameters '{"commands":["aws s3 cp s3://$S3_BUCKET_NAME/*.yml $DESTINATION_PATH/"], "executionTimeout":["3600"]}' \
          --region eu-west-1
